### ISSUE TITLE
Is it possible to have _some_ modification to state when an Agenda is rolled back?

### ISSUE THREAD

**Issue by sdd** [philpl/redux-fluorine#2]
Hey Phil,

Just trying to understand some use cases for redux-fluorine. If, say, an async fetch is performed in an agenda, and the fetch fails and the agenda rolls back, how can I track the error in the state, in order to show an error banner for example?

**Comment by kitten** [comment]
Normally when you'll want a one-off thing inside your component, you can use `do`:

``` js
dispatch(agenda.do(x => {
  // next
}, err => {
  // error
}, () => {
 // complete
}))
```

`finally` might also be interesting for loading states and there are a couple more which handle errors and completions.
